### ISSUE TITLE
membership.vanhack.ca has changing certificates

### ISSUE THREAD

**Issue by TyIsI** [vhs/vhs-door-nfc#1]
membership.vanhack.ca uses LetsEncrypt for HTTPS certificates, which change every 3 months.

This puts a limit on hardcoded certificates in the code.

**Comment by lukecyca** [comment]
This is fairly easily overcome by pinning the "Let’s Encrypt Authority X1" intermediate cert instead of a leaf cert. The leaf cert changes regularly, but will always be signed by this intermediate key which is likely to stay stable for a long time.

[In this thread](https://community.letsencrypt.org/t/hpkp-best-practices-if-you-choose-to-implement/4625) they discuss whether this intermediate cert will be stable _forever_. It sounds like LE is not guaranteeing that, but indicates it should be stable for a long time.

In the unlikely event it changes, we'd have to reflash our embedded device. Not a catastrophe.

**Comment by richard-sim** [comment]
I think we’re already good - we use the exact same cert for isvhsopen.com
and Nomos, even though they were extracted separately (and the code treats
them separately just in case)

**Comment by richard-sim** [comment]
Take a look at this file that has both the command and full cert chain to
see what we’re using. LMK if you think something still needs to change.

https://github.com/vhs/vhs-door-nfc/blob/master/software/esp32-firmware/src/nomos_cert.h

**Comment by lukecyca** [comment]
Looks like you are embedding "Let's Encrypt Authority X3" which is totally reasonable.

LE has already retired their X1 and X2 intermediates, so it's possible they'll retire this one eventually too. In that case we'd just have to reflash this one embedded device. Not the end of the world.

Nice work on this firmware, BTW!

**Comment by richard-sim** [comment]
Thanks! 👍 

Closing this issue as it looks like it's a non-issue, at least for now. :)
